// Immobilien-Lexikon: Begriffe für deutsche Vermieter und Investoren.
// Jeder Eintrag: Begriff, Definition (1-3 Sätze), optionaler Link zu vertiefendem
// Ratgeber-Artikel oder Rechner (verweisText + verweisHref).
export const GLOSSAR = [
  {
    begriff: 'Bruttomietrendite',
    definition: 'Die jährliche Kaltmiete geteilt durch den Kaufpreis der Immobilie, ohne Berücksichtigung von Kaufnebenkosten oder laufenden Kosten. Dient als schneller, aber grober erster Vergleichswert zwischen Objekten.',
    verweisText: 'Mietrendite berechnen: Der komplette Guide',
    verweisHref: '/ratgeber/mietrendite-berechnen',
  },
  {
    begriff: 'Nettomietrendite',
    definition: 'Die Jahreskaltmiete abzüglich nicht umlagefähiger Bewirtschaftungskosten, geteilt durch den Kaufpreis inklusive Kaufnebenkosten. Deutlich aussagekräftiger als die Bruttomietrendite, da sie die tatsächliche Kostenstruktur berücksichtigt.',
    verweisText: 'Mietrendite berechnen: Der komplette Guide',
    verweisHref: '/ratgeber/mietrendite-berechnen',
  },
  {
    begriff: 'Cash-on-Cash-Rendite',
    definition: 'Der jährliche Cashflow nach Finanzierungskosten geteilt durch das eingesetzte Eigenkapital. Zeigt, wie effizient das eigene Kapital arbeitet, insbesondere bei fremdfinanzierten Objekten.',
    verweisText: 'Cashflow bei Immobilien: Was Vermieter wissen müssen',
    verweisHref: '/ratgeber/cashflow-bei-immobilien',
  },
  {
    begriff: 'Cashflow',
    definition: 'Die monatliche Differenz zwischen Mieteinnahmen und allen laufenden Ausgaben (Finanzierungsrate, Bewirtschaftungskosten, Rücklagen). Ein positiver Cashflow bedeutet, die Immobilie trägt sich selbst.',
    verweisText: 'Cashflow bei Immobilien: Was Vermieter wissen müssen',
    verweisHref: '/ratgeber/cashflow-bei-immobilien',
  },
  {
    begriff: 'AfA (Absetzung für Abnutzung)',
    definition: 'Die steuerliche Abschreibung des Gebäudewerts einer vermieteten Immobilie über die Nutzungsdauer. Mindert jährlich das zu versteuernde Einkommen aus Vermietung und Verpachtung, typisch 2 bis 3 % pro Jahr je nach Baujahr.',
    verweisText: 'AfA-Rechner',
    verweisHref: '/afa-rechner',
  },
  {
    begriff: 'Sonder-AfA § 7b EStG',
    definition: 'Zusätzliche Abschreibung von 5 % pro Jahr über die ersten vier Jahre für neu gebaute Mietwohnungen mit Bauantrag ab 2023, sofern bestimmte Kosten- und Effizienzgrenzen eingehalten werden.',
    verweisText: 'AfA und Steuern bei Vermietung: Der Leitfaden',
    verweisHref: '/ratgeber/afa-und-steuern-vermietung',
  },
  {
    begriff: 'Grunderwerbsteuer',
    definition: 'Einmalige Steuer beim Eigentumswechsel einer Immobilie, die vom jeweiligen Bundesland festgelegt wird. Die Sätze reichen aktuell von 3,5 % in Bayern bis 6,5 % in mehreren Bundesländern.',
    verweisText: 'Grunderwerbsteuer-Rechner',
    verweisHref: '/grunderwerbsteuer-rechner',
  },
  {
    begriff: 'Grundsteuer',
    definition: 'Jährlich wiederkehrende kommunale Steuer auf Grundbesitz, berechnet aus Grundsteuerwert, Steuermesszahl und dem Hebesatz der Gemeinde. Seit der Reform 2025 gilt bundesweit ein neues Bewertungsrecht.',
    verweisText: 'Grundsteuerreform 2025: Was sich für Vermieter ändert',
    verweisHref: '/ratgeber/grundsteuerreform-2025-vermieter',
  },
  {
    begriff: 'Spekulationssteuer',
    definition: 'Umgangssprachlicher Begriff für die Besteuerung des Veräußerungsgewinns bei einem Immobilienverkauf innerhalb von 10 Jahren nach Anschaffung (§ 23 EStG). Bei durchgehender Eigennutzung entfällt sie.',
    verweisText: 'Spekulationssteuer bei Immobilienverkauf',
    verweisHref: '/ratgeber/spekulationssteuer-immobilienverkauf',
  },
  {
    begriff: 'Maklerprovision (Halbteilungsgrundsatz)',
    definition: 'Beim Immobilienkauf gilt seit 2020 der Halbteilungsgrundsatz nach § 656c BGB: Ist der Makler für beide Seiten tätig, wird die Provision hälftig zwischen Käufer und Verkäufer geteilt.',
    verweisText: 'Maklerprovision beim Immobilienkauf: Wer zahlt was?',
    verweisHref: '/ratgeber/maklerprovision-immobilienkauf',
  },
  {
    begriff: 'Bestellerprinzip',
    definition: 'Regel bei der Vermietung (nicht beim Kauf): Wer den Makler beauftragt, muss ihn auch bezahlen — meist also der Vermieter. Gilt seit 2015 für Mietverträge in Deutschland.',
    verweisText: 'Maklerprovision beim Immobilienkauf: Wer zahlt was?',
    verweisHref: '/ratgeber/maklerprovision-immobilienkauf',
  },
  {
    begriff: 'Nebenkostenabrechnung',
    definition: 'Die jährliche Abrechnung der umlagefähigen Betriebskosten zwischen Vermieter und Mieter, die dem Mieter spätestens 12 Monate nach Ende des Abrechnungszeitraums zugehen muss.',
    verweisText: 'Nebenkostenabrechnung für Vermieter',
    verweisHref: '/ratgeber/nebenkostenabrechnung-vermieter',
  },
  {
    begriff: 'Betriebskostenverordnung (BetrKV)',
    definition: 'Verordnung, die abschließend festlegt, welche Kostenarten als Betriebskosten auf Mieter umgelegt werden dürfen — etwa Grundsteuer, Versicherungen, Hausmeister und Müllabfuhr.',
    verweisText: 'Nebenkostenabrechnung für Vermieter',
    verweisHref: '/ratgeber/nebenkostenabrechnung-vermieter',
  },
  {
    begriff: 'Mietspiegel',
    definition: 'Übersicht über die ortsübliche Vergleichsmiete einer Gemeinde, gegliedert nach Wohnungsgröße, Lage, Ausstattung und Baujahr. Zentrale Grundlage für rechtssichere Mieterhöhungen.',
    verweisText: 'Mietspiegel verstehen und für Mieterhöhungen nutzen',
    verweisHref: '/ratgeber/mietspiegel-verstehen',
  },
  {
    begriff: 'Kappungsgrenze',
    definition: 'Begrenzt die Mieterhöhung auf die ortsübliche Vergleichsmiete: maximal 20 % innerhalb von drei Jahren, in Gebieten mit angespanntem Wohnungsmarkt maximal 15 %.',
    verweisText: 'Mietspiegel verstehen und für Mieterhöhungen nutzen',
    verweisHref: '/ratgeber/mietspiegel-verstehen',
  },
  {
    begriff: 'Mietpreisbremse',
    definition: 'Begrenzt in ausgewiesenen Gebieten mit angespanntem Wohnungsmarkt die Miete bei Neuvermietung auf maximal 10 % über der ortsüblichen Vergleichsmiete, mit gesetzlichen Ausnahmen etwa für Neubauten.',
    verweisText: 'Mietspiegel verstehen und für Mieterhöhungen nutzen',
    verweisHref: '/ratgeber/mietspiegel-verstehen',
  },
  {
    begriff: 'Modernisierungsumlage (§ 559 BGB)',
    definition: 'Erlaubt Vermietern, 8 % der Modernisierungskosten jährlich auf die Miete umzulegen, begrenzt durch eine Kappungsgrenze von 3 €/m² in sechs Jahren. Für Heizungstausch gilt seit 2024 eine Sonderregel mit 10 %.',
    verweisText: 'Mieterhöhung nach Modernisierung: § 559 BGB',
    verweisHref: '/ratgeber/mieterhoehung-modernisierung',
  },
  {
    begriff: 'Eigenbedarfskündigung',
    definition: 'Kündigungsgrund nach § 573 BGB, wenn der Vermieter die Wohnung für sich selbst oder nahe Angehörige benötigt. Erfordert eine konkrete, nachvollziehbare Begründung und die Einhaltung gestaffelter Kündigungsfristen.',
    verweisText: 'Kündigung wegen Eigenbedarf',
    verweisHref: '/ratgeber/eigenbedarfskuendigung',
  },
  {
    begriff: 'Mietkaution',
    definition: 'Sicherheitsleistung des Mieters von maximal drei Nettokaltmieten, die der Vermieter getrennt vom eigenen Vermögen und verzinst anlegen muss (§ 551 BGB).',
    verweisText: 'Mietkaution richtig anlegen: Pflichten nach § 551 BGB',
    verweisHref: '/ratgeber/kaution-richtig-anlegen',
  },
  {
    begriff: 'Untervermietung',
    definition: 'Überlassung eines Teils der Mietwohnung an Dritte, für die der Mieter grundsätzlich die Erlaubnis des Vermieters benötigt. Bei berechtigtem Interesse besteht ein gesetzlicher Anspruch darauf (§ 553 BGB).',
    verweisText: 'Untervermietung erlauben oder verbieten',
    verweisHref: '/ratgeber/untervermietung-erlauben-verbieten',
  },
  {
    begriff: 'Beleihungsauslauf',
    definition: 'Verhältnis der Darlehenssumme zum Beleihungswert der Immobilie, angegeben in Prozent. Ein niedrigerer Beleihungsauslauf führt in der Regel zu besseren Kreditkonditionen.',
    verweisText: 'Immobilienfinanzierung für Kapitalanleger',
    verweisHref: '/ratgeber/immobilienfinanzierung',
  },
  {
    begriff: 'Zinsbindung',
    definition: 'Zeitraum, für den der vereinbarte Sollzins eines Immobiliendarlehens festgeschrieben ist, häufig 10, 15 oder 20 Jahre. Nach Ablauf wird für die Restschuld eine Anschlussfinanzierung benötigt.',
    verweisText: 'Tilgungsplan-Rechner',
    verweisHref: '/tilgungsplan-rechner',
  },
  {
    begriff: 'Anschlussfinanzierung',
    definition: 'Neue Finanzierung der nach Ablauf der Zinsbindung verbleibenden Restschuld, zu den dann aktuellen Marktkonditionen — diese können höher oder niedriger als der ursprüngliche Zins ausfallen.',
    verweisText: 'Tilgungsplan-Rechner',
    verweisHref: '/tilgungsplan-rechner',
  },
  {
    begriff: 'Annuitätendarlehen',
    definition: 'Darlehensform mit über die Zinsbindung konstanter monatlicher Rate. Der Zinsanteil sinkt mit fallender Restschuld, der Tilgungsanteil steigt entsprechend.',
    verweisText: 'Tilgungsplan-Rechner',
    verweisHref: '/tilgungsplan-rechner',
  },
  {
    begriff: 'Tilgungssatz',
    definition: 'Prozentualer Anteil der Darlehenssumme, der anfänglich jährlich zurückgezahlt wird — üblich sind 1 bis 3 % pro Jahr. Ein höherer Tilgungssatz verkürzt die Kreditlaufzeit erheblich.',
    verweisText: 'Tilgungsplan-Rechner',
    verweisHref: '/tilgungsplan-rechner',
  },
  {
    begriff: 'Grundstücksanteil',
    definition: 'Der Teil des Kaufpreises, der auf Grund und Boden entfällt und nicht abschreibbar ist, da sich Grundstücke nicht abnutzen — typischerweise 15 bis 30 % je nach Lage und Bodenrichtwert.',
    verweisText: 'AfA-Rechner',
    verweisHref: '/afa-rechner',
  },
  {
    begriff: 'Kaufnebenkosten',
    definition: 'Zusatzkosten beim Immobilienerwerb neben dem Kaufpreis — vor allem Grunderwerbsteuer, Notar- und Grundbuchkosten sowie ggf. Maklerprovision. Liegen in Deutschland meist bei 8 bis 15 % des Kaufpreises.',
    verweisText: 'Kaufnebenkosten-Rechner',
    verweisHref: '/kaufnebenkosten-rechner',
  },
  {
    begriff: 'Erbschaftsteuer bei Immobilien',
    definition: 'Steuer auf den Erwerb einer Immobilie durch Erbschaft oder Schenkung, mit Freibeträgen von 20.000 bis 500.000 € je nach Verwandtschaftsgrad und einem 10-%-Abschlag für vermietete Objekte.',
    verweisText: 'Erbschaftsteuer und Schenkungsteuer bei Immobilien',
    verweisHref: '/ratgeber/erbschaftsteuer-immobilie',
  },
  {
    begriff: 'Gebäudemodernisierungsgesetz (GModG)',
    definition: 'Löst seit Juli 2026 das bisherige Gebäudeenergiegesetz (GEG) ab und ersetzt die starre 65-Prozent-Erneuerbare-Pflicht bei neuen Heizungen durch einen technologieoffeneren Rahmen.',
    verweisText: 'Vom GEG zum Gebäudemodernisierungsgesetz: Was sich 2026 ändert',
    verweisHref: '/ratgeber/geg-gmodg-vermieter-2026',
  },
];
